System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime"
    ]
  },
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "aurelia": [
      "github:aurelia/logging-console@0.8.0",
      "github:aurelia/logging-console@0.8.0/aurelia-logging-console",
      "github:aurelia/pal@0.2.0",
      "github:aurelia/logging@0.8.0",
      "github:aurelia/pal@0.2.0/aurelia-pal",
      "github:aurelia/logging@0.8.0/aurelia-logging",
      "github:aurelia/history-browser@0.9.0",
      "github:aurelia/history-browser@0.9.0/aurelia-history-browser",
      "npm:core-js@0.9.18",
      "github:aurelia/history@0.8.0",
      "npm:core-js@0.9.18/client/shim.min",
      "github:aurelia/history@0.8.0/aurelia-history",
      "github:jspm/nodelibs-process@0.1.2",
      "github:jspm/nodelibs-process@0.1.2/index",
      "npm:process@0.11.2",
      "npm:process@0.11.2/browser",
      "github:aurelia/loader-default@0.11.2",
      "github:aurelia/loader-default@0.11.2/aurelia-loader-default",
      "github:aurelia/loader@0.10.0",
      "github:aurelia/metadata@0.9.0",
      "github:aurelia/loader@0.10.0/aurelia-loader",
      "github:aurelia/metadata@0.9.0/aurelia-metadata",
      "npm:core-js@1.2.1",
      "github:aurelia/path@0.10.0",
      "npm:core-js@1.2.1/index",
      "github:aurelia/path@0.10.0/aurelia-path",
      "npm:core-js@1.2.1/shim",
      "npm:core-js@1.2.1/modules/core.dict",
      "npm:core-js@1.2.1/modules/core.get-iterator-method",
      "npm:core-js@1.2.1/modules/core.get-iterator",
      "npm:core-js@1.2.1/modules/core.is-iterable",
      "npm:core-js@1.2.1/modules/core.delay",
      "npm:core-js@1.2.1/modules/core.function.part",
      "npm:core-js@1.2.1/modules/core.object.is-object",
      "npm:core-js@1.2.1/modules/core.object.classof",
      "npm:core-js@1.2.1/modules/core.object.define",
      "npm:core-js@1.2.1/modules/core.object.make",
      "npm:core-js@1.2.1/modules/core.number.iterator",
      "npm:core-js@1.2.1/modules/core.string.escape-html",
      "npm:core-js@1.2.1/modules/core.string.unescape-html",
      "npm:core-js@1.2.1/modules/core.log",
      "npm:core-js@1.2.1/modules/$.core",
      "npm:core-js@1.2.1/modules/es5",
      "npm:core-js@1.2.1/modules/es6.symbol",
      "npm:core-js@1.2.1/modules/es6.object.assign",
      "npm:core-js@1.2.1/modules/es6.object.is",
      "npm:core-js@1.2.1/modules/es6.object.set-prototype-of",
      "npm:core-js@1.2.1/modules/es6.object.to-string",
      "npm:core-js@1.2.1/modules/es6.object.freeze",
      "npm:core-js@1.2.1/modules/es6.object.seal",
      "npm:core-js@1.2.1/modules/es6.object.prevent-extensions",
      "npm:core-js@1.2.1/modules/es6.object.is-frozen",
      "npm:core-js@1.2.1/modules/es6.object.is-sealed",
      "npm:core-js@1.2.1/modules/es6.object.is-extensible",
      "npm:core-js@1.2.1/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@1.2.1/modules/es6.object.get-prototype-of",
      "npm:core-js@1.2.1/modules/es6.object.keys",
      "npm:core-js@1.2.1/modules/es6.object.get-own-property-names",
      "npm:core-js@1.2.1/modules/es6.function.name",
      "npm:core-js@1.2.1/modules/es6.function.has-instance",
      "npm:core-js@1.2.1/modules/es6.number.constructor",
      "npm:core-js@1.2.1/modules/es6.number.epsilon",
      "npm:core-js@1.2.1/modules/es6.number.is-finite",
      "npm:core-js@1.2.1/modules/es6.number.is-integer",
      "npm:core-js@1.2.1/modules/es6.number.is-nan",
      "npm:core-js@1.2.1/modules/es6.number.is-safe-integer",
      "npm:core-js@1.2.1/modules/es6.number.max-safe-integer",
      "npm:core-js@1.2.1/modules/es6.number.min-safe-integer",
      "npm:core-js@1.2.1/modules/es6.number.parse-float",
      "npm:core-js@1.2.1/modules/es6.number.parse-int",
      "npm:core-js@1.2.1/modules/es6.math.acosh",
      "npm:core-js@1.2.1/modules/es6.math.asinh",
      "npm:core-js@1.2.1/modules/es6.math.atanh",
      "npm:core-js@1.2.1/modules/es6.math.cbrt",
      "npm:core-js@1.2.1/modules/es6.math.clz32",
      "npm:core-js@1.2.1/modules/es6.math.cosh",
      "npm:core-js@1.2.1/modules/es6.math.expm1",
      "npm:core-js@1.2.1/modules/es6.math.fround",
      "npm:core-js@1.2.1/modules/es6.math.hypot",
      "npm:core-js@1.2.1/modules/es6.math.imul",
      "npm:core-js@1.2.1/modules/es6.math.log10",
      "npm:core-js@1.2.1/modules/es6.math.log1p",
      "npm:core-js@1.2.1/modules/es6.math.log2",
      "npm:core-js@1.2.1/modules/es6.math.sign",
      "npm:core-js@1.2.1/modules/es6.math.sinh",
      "npm:core-js@1.2.1/modules/es6.math.tanh",
      "npm:core-js@1.2.1/modules/es6.math.trunc",
      "npm:core-js@1.2.1/modules/es6.string.from-code-point",
      "npm:core-js@1.2.1/modules/es6.string.raw",
      "npm:core-js@1.2.1/modules/es6.string.trim",
      "npm:core-js@1.2.1/modules/es6.string.iterator",
      "npm:core-js@1.2.1/modules/es6.string.code-point-at",
      "npm:core-js@1.2.1/modules/es6.string.ends-with",
      "npm:core-js@1.2.1/modules/es6.string.includes",
      "npm:core-js@1.2.1/modules/es6.string.repeat",
      "npm:core-js@1.2.1/modules/es6.string.starts-with",
      "npm:core-js@1.2.1/modules/es6.array.from",
      "npm:core-js@1.2.1/modules/es6.array.of",
      "npm:core-js@1.2.1/modules/es6.array.iterator",
      "npm:core-js@1.2.1/modules/es6.array.species",
      "npm:core-js@1.2.1/modules/es6.array.copy-within",
      "npm:core-js@1.2.1/modules/es6.array.fill",
      "npm:core-js@1.2.1/modules/es6.array.find",
      "npm:core-js@1.2.1/modules/es6.array.find-index",
      "npm:core-js@1.2.1/modules/es6.regexp.constructor",
      "npm:core-js@1.2.1/modules/es6.regexp.flags",
      "npm:core-js@1.2.1/modules/es6.regexp.match",
      "npm:core-js@1.2.1/modules/es6.regexp.replace",
      "npm:core-js@1.2.1/modules/es6.regexp.search",
      "npm:core-js@1.2.1/modules/es6.regexp.split",
      "npm:core-js@1.2.1/modules/es6.promise",
      "npm:core-js@1.2.1/modules/es6.map",
      "npm:core-js@1.2.1/modules/es6.set",
      "npm:core-js@1.2.1/modules/es6.weak-map",
      "npm:core-js@1.2.1/modules/es6.weak-set",
      "npm:core-js@1.2.1/modules/es6.reflect.apply",
      "npm:core-js@1.2.1/modules/es6.reflect.construct",
      "npm:core-js@1.2.1/modules/es6.reflect.define-property",
      "npm:core-js@1.2.1/modules/es6.reflect.delete-property",
      "npm:core-js@1.2.1/modules/es6.reflect.enumerate",
      "npm:core-js@1.2.1/modules/es6.reflect.get",
      "npm:core-js@1.2.1/modules/es6.reflect.get-own-property-descriptor",
      "npm:core-js@1.2.1/modules/es6.reflect.get-prototype-of",
      "npm:core-js@1.2.1/modules/es6.reflect.has",
      "npm:core-js@1.2.1/modules/es6.reflect.is-extensible",
      "npm:core-js@1.2.1/modules/es6.reflect.own-keys",
      "npm:core-js@1.2.1/modules/es6.reflect.prevent-extensions",
      "npm:core-js@1.2.1/modules/es6.reflect.set",
      "npm:core-js@1.2.1/modules/es6.reflect.set-prototype-of",
      "npm:core-js@1.2.1/modules/es7.array.includes",
      "npm:core-js@1.2.1/modules/es7.string.at",
      "npm:core-js@1.2.1/modules/es7.string.pad-left",
      "npm:core-js@1.2.1/modules/es7.string.pad-right",
      "npm:core-js@1.2.1/modules/es7.string.trim-left",
      "npm:core-js@1.2.1/modules/es7.string.trim-right",
      "npm:core-js@1.2.1/modules/es7.regexp.escape",
      "npm:core-js@1.2.1/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@1.2.1/modules/es7.object.values",
      "npm:core-js@1.2.1/modules/es7.object.entries",
      "npm:core-js@1.2.1/modules/es7.map.to-json",
      "npm:core-js@1.2.1/modules/es7.set.to-json",
      "npm:core-js@1.2.1/modules/js.array.statics",
      "npm:core-js@1.2.1/modules/web.timers",
      "npm:core-js@1.2.1/modules/web.immediate",
      "npm:core-js@1.2.1/modules/web.dom.iterable",
      "npm:core-js@1.2.1/modules/$",
      "npm:core-js@1.2.1/modules/$.ctx",
      "npm:core-js@1.2.1/modules/$.def",
      "npm:core-js@1.2.1/modules/$.property-desc",
      "npm:core-js@1.2.1/modules/$.assign",
      "npm:core-js@1.2.1/modules/$.keyof",
      "npm:core-js@1.2.1/modules/$.a-function",
      "npm:core-js@1.2.1/modules/$.for-of",
      "npm:core-js@1.2.1/modules/$.iter-step",
      "npm:core-js@1.2.1/modules/$.is-object",
      "npm:core-js@1.2.1/modules/$.to-iobject",
      "npm:core-js@1.2.1/modules/$.support-desc",
      "npm:core-js@1.2.1/modules/$.has",
      "npm:core-js@1.2.1/modules/$.iter-create",
      "npm:core-js@1.2.1/modules/$.classof",
      "npm:core-js@1.2.1/modules/$.wks",
      "npm:core-js@1.2.1/modules/$.iterators",
      "npm:core-js@1.2.1/modules/$.an-object",
      "npm:core-js@1.2.1/modules/$.global",
      "npm:core-js@1.2.1/modules/$.partial",
      "npm:core-js@1.2.1/modules/$.path",
      "npm:core-js@1.2.1/modules/$.object-define",
      "npm:core-js@1.2.1/modules/$.iter-define",
      "npm:core-js@1.2.1/modules/$.replacer",
      "npm:core-js@1.2.1/modules/$.html",
      "npm:core-js@1.2.1/modules/$.dom-create",
      "npm:core-js@1.2.1/modules/$.cof",
      "npm:core-js@1.2.1/modules/$.invoke",
      "npm:core-js@1.2.1/modules/$.array-methods",
      "npm:core-js@1.2.1/modules/$.uid",
      "npm:core-js@1.2.1/modules/$.to-object",
      "npm:core-js@1.2.1/modules/$.to-integer",
      "npm:core-js@1.2.1/modules/$.to-index",
      "npm:core-js@1.2.1/modules/$.to-length",
      "npm:core-js@1.2.1/modules/$.iobject",
      "npm:core-js@1.2.1/modules/$.fails",
      "npm:core-js@1.2.1/modules/$.array-includes",
      "npm:core-js@1.2.1/modules/$.is-array",
      "npm:core-js@1.2.1/modules/$.redef",
      "npm:core-js@1.2.1/modules/$.shared",
      "npm:core-js@1.2.1/modules/$.tag",
      "npm:core-js@1.2.1/modules/$.get-names",
      "npm:core-js@1.2.1/modules/$.enum-keys",
      "npm:core-js@1.2.1/modules/$.library",
      "npm:core-js@1.2.1/modules/$.same",
      "npm:core-js@1.2.1/modules/$.set-proto",
      "npm:core-js@1.2.1/modules/$.object-sap",
      "npm:core-js@1.2.1/modules/$.is-integer",
      "npm:core-js@1.2.1/modules/$.log1p",
      "npm:core-js@1.2.1/modules/$.sign",
      "npm:core-js@1.2.1/modules/$.expm1",
      "npm:core-js@1.2.1/modules/$.string-trim",
      "npm:core-js@1.2.1/modules/$.string-at",
      "npm:core-js@1.2.1/modules/$.string-context",
      "npm:core-js@1.2.1/modules/$.fails-is-regexp",
      "npm:core-js@1.2.1/modules/$.string-repeat",
      "npm:core-js@1.2.1/modules/$.iter-call",
      "npm:core-js@1.2.1/modules/$.is-array-iter",
      "npm:core-js@1.2.1/modules/$.iter-detect",
      "npm:core-js@1.2.1/modules/$.unscope",
      "npm:core-js@1.2.1/modules/$.species",
      "npm:core-js@1.2.1/modules/$.array-copy-within",
      "npm:core-js@1.2.1/modules/$.array-fill",
      "npm:core-js@1.2.1/modules/$.is-regexp",
      "npm:core-js@1.2.1/modules/$.flags",
      "npm:core-js@1.2.1/modules/$.fix-re-wks",
      "npm:core-js@1.2.1/modules/$.strict-new",
      "npm:core-js@1.2.1/modules/$.microtask",
      "npm:core-js@1.2.1/modules/$.mix",
      "npm:core-js@1.2.1/modules/$.collection-strong",
      "npm:core-js@1.2.1/modules/$.collection",
      "npm:core-js@1.2.1/modules/$.collection-weak",
      "npm:core-js@1.2.1/modules/$.own-keys",
      "npm:core-js@1.2.1/modules/$.string-pad",
      "npm:core-js@1.2.1/modules/$.object-to-array",
      "npm:core-js@1.2.1/modules/$.collection-to-json",
      "npm:core-js@1.2.1/modules/$.task",
      "npm:core-js@1.2.1/modules/$.hide",
      "npm:core-js@1.2.1/modules/$.defined",
      "github:aurelia/templating-router@0.17.0",
      "github:aurelia/templating-router@0.17.0/aurelia-templating-router",
      "github:aurelia/router@0.13.0",
      "github:aurelia/router@0.13.0/aurelia-router",
      "github:aurelia/dependency-injection@0.11.2",
      "github:aurelia/route-recognizer@0.8.0",
      "github:aurelia/event-aggregator@0.9.0",
      "github:aurelia/dependency-injection@0.11.2/aurelia-dependency-injection",
      "github:aurelia/route-recognizer@0.8.0/aurelia-route-recognizer",
      "github:aurelia/event-aggregator@0.9.0/aurelia-event-aggregator",
      "github:aurelia/templating-router@0.17.0/route-loader",
      "github:aurelia/templating@0.16.0",
      "github:aurelia/templating@0.16.0/aurelia-templating",
      "github:aurelia/binding@0.10.1",
      "github:aurelia/task-queue@0.8.0",
      "github:aurelia/binding@0.10.1/aurelia-binding",
      "github:aurelia/task-queue@0.8.0/aurelia-task-queue",
      "github:aurelia/templating-router@0.17.0/router-view",
      "github:aurelia/templating-router@0.17.0/route-href",
      "github:aurelia/templating-resources@0.16.1",
      "github:aurelia/templating-resources@0.16.1/aurelia-templating-resources",
      "github:aurelia/templating-resources@0.16.1/compose",
      "github:aurelia/templating-resources@0.16.1/if",
      "github:aurelia/templating-resources@0.16.1/with",
      "github:aurelia/templating-resources@0.16.1/repeat",
      "github:aurelia/templating-resources@0.16.1/show",
      "github:aurelia/templating-resources@0.16.1/global-behavior",
      "github:aurelia/templating-resources@0.16.1/sanitize-html",
      "github:aurelia/templating-resources@0.16.1/replaceable",
      "github:aurelia/templating-resources@0.16.1/focus",
      "github:aurelia/templating-resources@0.16.1/compile-spy",
      "github:aurelia/templating-resources@0.16.1/view-spy",
      "github:aurelia/templating-resources@0.16.1/dynamic-element",
      "github:aurelia/templating-resources@0.16.1/html-sanitizer",
      "github:aurelia/templating-resources@0.16.1/css-resource",
      "github:aurelia/templating-binding@0.16.1",
      "github:aurelia/templating-binding@0.16.1/aurelia-templating-binding",
      "github:aurelia/animator-css@0.17.0",
      "github:aurelia/animator-css@0.17.0/aurelia-animator-css",
      "github:aurelia/fetch-client@0.3.0",
      "github:aurelia/fetch-client@0.3.0/aurelia-fetch-client",
      "github:aurelia/bootstrapper@0.18.0",
      "github:aurelia/bootstrapper@0.18.0/aurelia-bootstrapper",
      "github:aurelia/pal-browser@0.2.0",
      "github:aurelia/pal-browser@0.2.0/aurelia-pal-browser"
    ],
    "app-build": [
      "github:twbs/bootstrap@3.3.5/css/bootstrap.css!github:systemjs/plugin-text@0.0.2",
      "select-picker.html!github:systemjs/plugin-text@0.0.2",
      "resources.html!github:systemjs/plugin-text@0.0.2",
      "nav-bar.html!github:systemjs/plugin-text@0.0.2",
      "app.html!github:systemjs/plugin-text@0.0.2",
      "select-picker",
      "github:aurelia/framework@0.17.0",
      "github:aurelia/framework@0.17.0/aurelia-framework",
      "npm:core-js@0.9.18",
      "github:aurelia/logging@0.8.0",
      "github:aurelia/templating@0.16.0",
      "github:aurelia/path@0.10.0",
      "github:aurelia/dependency-injection@0.11.2",
      "github:aurelia/loader@0.10.0",
      "github:aurelia/pal@0.2.0",
      "github:aurelia/binding@0.10.1",
      "github:aurelia/metadata@0.9.0",
      "github:aurelia/task-queue@0.8.0",
      "npm:core-js@0.9.18/client/shim.min",
      "github:aurelia/logging@0.8.0/aurelia-logging",
      "github:aurelia/templating@0.16.0/aurelia-templating",
      "github:aurelia/path@0.10.0/aurelia-path",
      "github:aurelia/dependency-injection@0.11.2/aurelia-dependency-injection",
      "github:aurelia/loader@0.10.0/aurelia-loader",
      "github:aurelia/pal@0.2.0/aurelia-pal",
      "github:aurelia/binding@0.10.1/aurelia-binding",
      "github:aurelia/metadata@0.9.0/aurelia-metadata",
      "github:aurelia/task-queue@0.8.0/aurelia-task-queue",
      "github:jspm/nodelibs-process@0.1.2",
      "npm:core-js@1.2.1",
      "github:jspm/nodelibs-process@0.1.2/index",
      "npm:core-js@1.2.1/index",
      "npm:process@0.11.2",
      "npm:core-js@1.2.1/shim",
      "npm:core-js@1.2.1/modules/core.dict",
      "npm:core-js@1.2.1/modules/core.get-iterator-method",
      "npm:core-js@1.2.1/modules/core.get-iterator",
      "npm:core-js@1.2.1/modules/core.is-iterable",
      "npm:core-js@1.2.1/modules/core.delay",
      "npm:core-js@1.2.1/modules/core.function.part",
      "npm:core-js@1.2.1/modules/core.object.is-object",
      "npm:core-js@1.2.1/modules/core.object.classof",
      "npm:core-js@1.2.1/modules/core.object.define",
      "npm:core-js@1.2.1/modules/core.object.make",
      "npm:core-js@1.2.1/modules/core.number.iterator",
      "npm:core-js@1.2.1/modules/core.string.escape-html",
      "npm:core-js@1.2.1/modules/core.string.unescape-html",
      "npm:core-js@1.2.1/modules/core.log",
      "npm:core-js@1.2.1/modules/$.core",
      "npm:process@0.11.2/browser",
      "npm:core-js@1.2.1/modules/es5",
      "npm:core-js@1.2.1/modules/es6.symbol",
      "npm:core-js@1.2.1/modules/es6.object.assign",
      "npm:core-js@1.2.1/modules/es6.object.is",
      "npm:core-js@1.2.1/modules/es6.object.set-prototype-of",
      "npm:core-js@1.2.1/modules/es6.object.to-string",
      "npm:core-js@1.2.1/modules/es6.object.freeze",
      "npm:core-js@1.2.1/modules/es6.object.seal",
      "npm:core-js@1.2.1/modules/es6.object.prevent-extensions",
      "npm:core-js@1.2.1/modules/es6.object.is-frozen",
      "npm:core-js@1.2.1/modules/es6.object.is-sealed",
      "npm:core-js@1.2.1/modules/es6.object.is-extensible",
      "npm:core-js@1.2.1/modules/es6.object.get-own-property-descriptor",
      "npm:core-js@1.2.1/modules/es6.object.get-prototype-of",
      "npm:core-js@1.2.1/modules/es6.object.keys",
      "npm:core-js@1.2.1/modules/es6.object.get-own-property-names",
      "npm:core-js@1.2.1/modules/es6.function.name",
      "npm:core-js@1.2.1/modules/es6.function.has-instance",
      "npm:core-js@1.2.1/modules/es6.number.constructor",
      "npm:core-js@1.2.1/modules/es6.number.epsilon",
      "npm:core-js@1.2.1/modules/es6.number.is-finite",
      "npm:core-js@1.2.1/modules/es6.number.is-integer",
      "npm:core-js@1.2.1/modules/es6.number.is-nan",
      "npm:core-js@1.2.1/modules/es6.number.is-safe-integer",
      "npm:core-js@1.2.1/modules/es6.number.max-safe-integer",
      "npm:core-js@1.2.1/modules/es6.number.min-safe-integer",
      "npm:core-js@1.2.1/modules/es6.number.parse-float",
      "npm:core-js@1.2.1/modules/es6.number.parse-int",
      "npm:core-js@1.2.1/modules/es6.math.acosh",
      "npm:core-js@1.2.1/modules/es6.math.asinh",
      "npm:core-js@1.2.1/modules/es6.math.atanh",
      "npm:core-js@1.2.1/modules/es6.math.cbrt",
      "npm:core-js@1.2.1/modules/es6.math.clz32",
      "npm:core-js@1.2.1/modules/es6.math.cosh",
      "npm:core-js@1.2.1/modules/es6.math.expm1",
      "npm:core-js@1.2.1/modules/es6.math.fround",
      "npm:core-js@1.2.1/modules/es6.math.hypot",
      "npm:core-js@1.2.1/modules/es6.math.imul",
      "npm:core-js@1.2.1/modules/es6.math.log10",
      "npm:core-js@1.2.1/modules/es6.math.log1p",
      "npm:core-js@1.2.1/modules/es6.math.log2",
      "npm:core-js@1.2.1/modules/es6.math.sign",
      "npm:core-js@1.2.1/modules/es6.math.sinh",
      "npm:core-js@1.2.1/modules/es6.math.tanh",
      "npm:core-js@1.2.1/modules/es6.math.trunc",
      "npm:core-js@1.2.1/modules/es6.string.from-code-point",
      "npm:core-js@1.2.1/modules/es6.string.raw",
      "npm:core-js@1.2.1/modules/es6.string.trim",
      "npm:core-js@1.2.1/modules/es6.string.iterator",
      "npm:core-js@1.2.1/modules/es6.string.code-point-at",
      "npm:core-js@1.2.1/modules/es6.string.ends-with",
      "npm:core-js@1.2.1/modules/es6.string.includes",
      "npm:core-js@1.2.1/modules/es6.string.repeat",
      "npm:core-js@1.2.1/modules/es6.string.starts-with",
      "npm:core-js@1.2.1/modules/es6.array.from",
      "npm:core-js@1.2.1/modules/es6.array.of",
      "npm:core-js@1.2.1/modules/es6.array.iterator",
      "npm:core-js@1.2.1/modules/es6.array.species",
      "npm:core-js@1.2.1/modules/es6.array.copy-within",
      "npm:core-js@1.2.1/modules/es6.array.fill",
      "npm:core-js@1.2.1/modules/es6.array.find",
      "npm:core-js@1.2.1/modules/es6.array.find-index",
      "npm:core-js@1.2.1/modules/es6.regexp.constructor",
      "npm:core-js@1.2.1/modules/es6.regexp.flags",
      "npm:core-js@1.2.1/modules/es6.regexp.match",
      "npm:core-js@1.2.1/modules/es6.regexp.replace",
      "npm:core-js@1.2.1/modules/es6.regexp.search",
      "npm:core-js@1.2.1/modules/es6.regexp.split",
      "npm:core-js@1.2.1/modules/es6.promise",
      "npm:core-js@1.2.1/modules/es6.map",
      "npm:core-js@1.2.1/modules/es6.set",
      "npm:core-js@1.2.1/modules/es6.weak-map",
      "npm:core-js@1.2.1/modules/es6.weak-set",
      "npm:core-js@1.2.1/modules/es6.reflect.apply",
      "npm:core-js@1.2.1/modules/es6.reflect.construct",
      "npm:core-js@1.2.1/modules/es6.reflect.define-property",
      "npm:core-js@1.2.1/modules/es6.reflect.delete-property",
      "npm:core-js@1.2.1/modules/es6.reflect.enumerate",
      "npm:core-js@1.2.1/modules/es6.reflect.get",
      "npm:core-js@1.2.1/modules/es6.reflect.get-own-property-descriptor",
      "npm:core-js@1.2.1/modules/es6.reflect.get-prototype-of",
      "npm:core-js@1.2.1/modules/es6.reflect.has",
      "npm:core-js@1.2.1/modules/es6.reflect.is-extensible",
      "npm:core-js@1.2.1/modules/es6.reflect.own-keys",
      "npm:core-js@1.2.1/modules/es6.reflect.prevent-extensions",
      "npm:core-js@1.2.1/modules/es6.reflect.set",
      "npm:core-js@1.2.1/modules/es6.reflect.set-prototype-of",
      "npm:core-js@1.2.1/modules/es7.array.includes",
      "npm:core-js@1.2.1/modules/es7.string.at",
      "npm:core-js@1.2.1/modules/es7.string.pad-left",
      "npm:core-js@1.2.1/modules/es7.string.pad-right",
      "npm:core-js@1.2.1/modules/es7.string.trim-left",
      "npm:core-js@1.2.1/modules/es7.string.trim-right",
      "npm:core-js@1.2.1/modules/es7.regexp.escape",
      "npm:core-js@1.2.1/modules/es7.object.get-own-property-descriptors",
      "npm:core-js@1.2.1/modules/es7.object.values",
      "npm:core-js@1.2.1/modules/es7.object.entries",
      "npm:core-js@1.2.1/modules/es7.map.to-json",
      "npm:core-js@1.2.1/modules/es7.set.to-json",
      "npm:core-js@1.2.1/modules/js.array.statics",
      "npm:core-js@1.2.1/modules/web.timers",
      "npm:core-js@1.2.1/modules/web.immediate",
      "npm:core-js@1.2.1/modules/web.dom.iterable",
      "npm:core-js@1.2.1/modules/$",
      "npm:core-js@1.2.1/modules/$.ctx",
      "npm:core-js@1.2.1/modules/$.def",
      "npm:core-js@1.2.1/modules/$.property-desc",
      "npm:core-js@1.2.1/modules/$.assign",
      "npm:core-js@1.2.1/modules/$.keyof",
      "npm:core-js@1.2.1/modules/$.a-function",
      "npm:core-js@1.2.1/modules/$.for-of",
      "npm:core-js@1.2.1/modules/$.iter-step",
      "npm:core-js@1.2.1/modules/$.is-object",
      "npm:core-js@1.2.1/modules/$.to-iobject",
      "npm:core-js@1.2.1/modules/$.support-desc",
      "npm:core-js@1.2.1/modules/$.has",
      "npm:core-js@1.2.1/modules/$.iter-create",
      "npm:core-js@1.2.1/modules/$.classof",
      "npm:core-js@1.2.1/modules/$.wks",
      "npm:core-js@1.2.1/modules/$.iterators",
      "npm:core-js@1.2.1/modules/$.an-object",
      "npm:core-js@1.2.1/modules/$.global",
      "npm:core-js@1.2.1/modules/$.partial",
      "npm:core-js@1.2.1/modules/$.path",
      "npm:core-js@1.2.1/modules/$.object-define",
      "npm:core-js@1.2.1/modules/$.iter-define",
      "npm:core-js@1.2.1/modules/$.replacer",
      "npm:core-js@1.2.1/modules/$.html",
      "npm:core-js@1.2.1/modules/$.dom-create",
      "npm:core-js@1.2.1/modules/$.cof",
      "npm:core-js@1.2.1/modules/$.invoke",
      "npm:core-js@1.2.1/modules/$.array-methods",
      "npm:core-js@1.2.1/modules/$.uid",
      "npm:core-js@1.2.1/modules/$.to-object",
      "npm:core-js@1.2.1/modules/$.to-integer",
      "npm:core-js@1.2.1/modules/$.to-index",
      "npm:core-js@1.2.1/modules/$.to-length",
      "npm:core-js@1.2.1/modules/$.iobject",
      "npm:core-js@1.2.1/modules/$.fails",
      "npm:core-js@1.2.1/modules/$.array-includes",
      "npm:core-js@1.2.1/modules/$.is-array",
      "npm:core-js@1.2.1/modules/$.redef",
      "npm:core-js@1.2.1/modules/$.shared",
      "npm:core-js@1.2.1/modules/$.tag",
      "npm:core-js@1.2.1/modules/$.get-names",
      "npm:core-js@1.2.1/modules/$.enum-keys",
      "npm:core-js@1.2.1/modules/$.library",
      "npm:core-js@1.2.1/modules/$.same",
      "npm:core-js@1.2.1/modules/$.set-proto",
      "npm:core-js@1.2.1/modules/$.object-sap",
      "npm:core-js@1.2.1/modules/$.is-integer",
      "npm:core-js@1.2.1/modules/$.log1p",
      "npm:core-js@1.2.1/modules/$.sign",
      "npm:core-js@1.2.1/modules/$.expm1",
      "npm:core-js@1.2.1/modules/$.string-trim",
      "npm:core-js@1.2.1/modules/$.string-at",
      "npm:core-js@1.2.1/modules/$.string-context",
      "npm:core-js@1.2.1/modules/$.fails-is-regexp",
      "npm:core-js@1.2.1/modules/$.string-repeat",
      "npm:core-js@1.2.1/modules/$.iter-call",
      "npm:core-js@1.2.1/modules/$.is-array-iter",
      "npm:core-js@1.2.1/modules/$.iter-detect",
      "npm:core-js@1.2.1/modules/$.unscope",
      "npm:core-js@1.2.1/modules/$.species",
      "npm:core-js@1.2.1/modules/$.array-copy-within",
      "npm:core-js@1.2.1/modules/$.array-fill",
      "npm:core-js@1.2.1/modules/$.is-regexp",
      "npm:core-js@1.2.1/modules/$.flags",
      "npm:core-js@1.2.1/modules/$.fix-re-wks",
      "npm:core-js@1.2.1/modules/$.strict-new",
      "npm:core-js@1.2.1/modules/$.microtask",
      "npm:core-js@1.2.1/modules/$.mix",
      "npm:core-js@1.2.1/modules/$.collection-strong",
      "npm:core-js@1.2.1/modules/$.collection",
      "npm:core-js@1.2.1/modules/$.collection-weak",
      "npm:core-js@1.2.1/modules/$.own-keys",
      "npm:core-js@1.2.1/modules/$.string-pad",
      "npm:core-js@1.2.1/modules/$.object-to-array",
      "npm:core-js@1.2.1/modules/$.collection-to-json",
      "npm:core-js@1.2.1/modules/$.task",
      "npm:core-js@1.2.1/modules/$.hide",
      "npm:core-js@1.2.1/modules/$.defined",
      "github:brianreavis/selectize.js@0.12.1",
      "github:jquery/jquery@2.1.4",
      "github:jquery/jquery@2.1.4/jquery",
      "github:brianreavis/selectize.js@0.12.1/js/selectize",
      "github:components/jquery@2.1.4",
      "github:components/jquery@2.1.4/jquery",
      "github:brianreavis/selectize.js@0.12.1/css/selectize.css!github:systemjs/plugin-css@0.1.18",
      "github:jquery/jquery@2.1.4/selector",
      "github:jquery/jquery@2.1.4/core",
      "github:jquery/jquery@2.1.4/traversing",
      "github:jquery/jquery@2.1.4/callbacks",
      "github:jquery/jquery@2.1.4/deferred",
      "github:jquery/jquery@2.1.4/core/ready",
      "github:jquery/jquery@2.1.4/data",
      "github:jquery/jquery@2.1.4/queue",
      "github:jquery/jquery@2.1.4/queue/delay",
      "github:jquery/jquery@2.1.4/attributes",
      "github:jquery/jquery@2.1.4/event",
      "github:jquery/jquery@2.1.4/event/alias",
      "github:jquery/jquery@2.1.4/manipulation",
      "github:jquery/jquery@2.1.4/manipulation/_evalUrl",
      "github:jquery/jquery@2.1.4/wrap",
      "github:jquery/jquery@2.1.4/css",
      "github:jquery/jquery@2.1.4/css/hiddenVisibleSelectors",
      "github:jquery/jquery@2.1.4/serialize",
      "github:jquery/jquery@2.1.4/ajax",
      "github:jquery/jquery@2.1.4/ajax/xhr",
      "github:jquery/jquery@2.1.4/ajax/script",
      "github:jquery/jquery@2.1.4/ajax/jsonp",
      "github:jquery/jquery@2.1.4/ajax/load",
      "github:jquery/jquery@2.1.4/event/ajax",
      "github:jquery/jquery@2.1.4/effects",
      "github:jquery/jquery@2.1.4/effects/animatedSelector",
      "github:jquery/jquery@2.1.4/offset",
      "github:jquery/jquery@2.1.4/dimensions",
      "github:jquery/jquery@2.1.4/deprecated",
      "github:jquery/jquery@2.1.4/exports/amd",
      "github:jquery/jquery@2.1.4/exports/global",
      "github:brianreavis/sifter.js@0.4.4",
      "npm:microplugin@0.0.3",
      "github:jquery/jquery@2.1.4/selector-sizzle",
      "github:jquery/jquery@2.1.4/var/slice",
      "github:jquery/jquery@2.1.4/var/arr",
      "github:jquery/jquery@2.1.4/var/concat",
      "github:jquery/jquery@2.1.4/var/push",
      "github:jquery/jquery@2.1.4/var/indexOf",
      "github:jquery/jquery@2.1.4/var/class2type",
      "github:jquery/jquery@2.1.4/var/toString",
      "github:jquery/jquery@2.1.4/var/hasOwn",
      "github:jquery/jquery@2.1.4/var/support",
      "github:jquery/jquery@2.1.4/traversing/var/rneedsContext",
      "github:jquery/jquery@2.1.4/core/init",
      "github:jquery/jquery@2.1.4/traversing/findFilter",
      "github:jquery/jquery@2.1.4/var/rnotwhite",
      "github:jquery/jquery@2.1.4/core/access",
      "github:jquery/jquery@2.1.4/data/var/data_priv",
      "github:jquery/jquery@2.1.4/data/var/data_user",
      "github:jquery/jquery@2.1.4/attributes/attr",
      "github:jquery/jquery@2.1.4/attributes/prop",
      "github:jquery/jquery@2.1.4/attributes/classes",
      "github:jquery/jquery@2.1.4/attributes/val",
      "github:jquery/jquery@2.1.4/var/strundefined",
      "github:jquery/jquery@2.1.4/event/support",
      "github:jquery/jquery@2.1.4/data/accepts",
      "github:jquery/jquery@2.1.4/manipulation/support",
      "github:jquery/jquery@2.1.4/manipulation/var/rcheckableType",
      "github:jquery/jquery@2.1.4/var/pnum",
      "github:jquery/jquery@2.1.4/css/var/rnumnonpx",
      "github:jquery/jquery@2.1.4/css/var/rmargin",
      "github:jquery/jquery@2.1.4/css/var/cssExpand",
      "github:jquery/jquery@2.1.4/css/var/getStyles",
      "github:jquery/jquery@2.1.4/css/var/isHidden",
      "github:jquery/jquery@2.1.4/css/curCSS",
      "github:jquery/jquery@2.1.4/css/defaultDisplay",
      "github:jquery/jquery@2.1.4/css/addGetHookIf",
      "github:jquery/jquery@2.1.4/css/support",
      "github:jquery/jquery@2.1.4/css/swap",
      "github:jquery/jquery@2.1.4/ajax/var/nonce",
      "github:jquery/jquery@2.1.4/ajax/var/rquery",
      "github:jquery/jquery@2.1.4/ajax/parseJSON",
      "github:jquery/jquery@2.1.4/core/parseHTML",
      "github:jquery/jquery@2.1.4/ajax/parseXML",
      "github:jquery/jquery@2.1.4/effects/Tween",
      "github:brianreavis/sifter.js@0.4.4/sifter",
      "npm:microplugin@0.0.3/microplugin",
      "github:jquery/jquery@2.1.4/sizzle/dist/sizzle",
      "github:jquery/jquery@2.1.4/core/var/rsingleTag",
      "github:jquery/jquery@2.1.4/data/Data",
      "github:jquery/jquery@2.1.4/attributes/support",
      "resources",
      "npm:base64-js@0.0.8",
      "npm:base64-js@0.0.8/lib/b64",
      "main",
      "github:twbs/bootstrap@3.3.5",
      "github:twbs/bootstrap@3.3.5/js/bootstrap",
      "github:brianreavis/selectize.js@0.12.1/css/selectize.bootstrap3.css!github:systemjs/plugin-css@0.1.18",
      "blur-image",
      "app"
    ]
  },

  map: {
    "aurelia-animator-css": "github:aurelia/animator-css@0.17.0",
    "aurelia-binding": "github:aurelia/binding@0.10.1",
    "aurelia-bootstrapper": "github:aurelia/bootstrapper@0.18.0",
    "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.11.2",
    "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.9.0",
    "aurelia-fetch-client": "github:aurelia/fetch-client@0.3.0",
    "aurelia-framework": "github:aurelia/framework@0.17.0",
    "aurelia-history": "github:aurelia/history@0.8.0",
    "aurelia-history-browser": "github:aurelia/history-browser@0.9.0",
    "aurelia-loader": "github:aurelia/loader@0.10.0",
    "aurelia-loader-default": "github:aurelia/loader-default@0.11.2",
    "aurelia-logging": "github:aurelia/logging@0.8.0",
    "aurelia-metadata": "github:aurelia/metadata@0.9.0",
    "aurelia-pal": "github:aurelia/pal@0.2.0",
    "aurelia-pal-browser": "github:aurelia/pal-browser@0.2.0",
    "aurelia-path": "github:aurelia/path@0.10.0",
    "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.8.0",
    "aurelia-router": "github:aurelia/router@0.13.0",
    "aurelia-task-queue": "github:aurelia/task-queue@0.8.0",
    "aurelia-templating": "github:aurelia/templating@0.16.0",
    "aurelia-templating-binding": "github:aurelia/templating-binding@0.16.1",
    "aurelia-templating-resources": "github:aurelia/templating-resources@0.16.1",
    "aurelia-templating-router": "github:aurelia/templating-router@0.17.0",
    "babel": "npm:babel-core@5.8.25",
    "babel-runtime": "npm:babel-runtime@5.8.25",
    "base64-js": "npm:base64-js@0.0.8",
    "bootstrap": "github:twbs/bootstrap@3.3.5",
    "clean-css": "npm:clean-css@3.4.6",
    "core-js": "npm:core-js@1.2.1",
    "css": "github:systemjs/plugin-css@0.1.18",
    "fetch": "github:github/fetch@0.9.0",
    "font-awesome": "npm:font-awesome@4.4.0",
    "jquery": "github:jquery/jquery@2.1.4",
    "selectize": "github:brianreavis/selectize.js@0.12.1",
    "text": "github:systemjs/plugin-text@0.0.2",
    "github:aurelia/animator-css@0.17.0": {
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "aurelia-templating": "github:aurelia/templating@0.16.0"
    },
    "github:aurelia/binding@0.10.1": {
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.8.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/bootstrapper@0.18.0": {
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.9.0",
      "aurelia-framework": "github:aurelia/framework@0.17.0",
      "aurelia-history": "github:aurelia/history@0.8.0",
      "aurelia-history-browser": "github:aurelia/history-browser@0.9.0",
      "aurelia-loader-default": "github:aurelia/loader-default@0.11.2",
      "aurelia-logging-console": "github:aurelia/logging-console@0.8.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "aurelia-pal-browser": "github:aurelia/pal-browser@0.2.0",
      "aurelia-router": "github:aurelia/router@0.13.0",
      "aurelia-templating": "github:aurelia/templating@0.16.0",
      "aurelia-templating-binding": "github:aurelia/templating-binding@0.16.1",
      "aurelia-templating-resources": "github:aurelia/templating-resources@0.16.1",
      "aurelia-templating-router": "github:aurelia/templating-router@0.17.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/dependency-injection@0.11.2": {
      "aurelia-logging": "github:aurelia/logging@0.8.0",
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/event-aggregator@0.9.0": {
      "aurelia-logging": "github:aurelia/logging@0.8.0"
    },
    "github:aurelia/fetch-client@0.3.0": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/framework@0.17.0": {
      "aurelia-binding": "github:aurelia/binding@0.10.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.11.2",
      "aurelia-loader": "github:aurelia/loader@0.10.0",
      "aurelia-logging": "github:aurelia/logging@0.8.0",
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "aurelia-path": "github:aurelia/path@0.10.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.8.0",
      "aurelia-templating": "github:aurelia/templating@0.16.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/history-browser@0.9.0": {
      "aurelia-history": "github:aurelia/history@0.8.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/loader-default@0.11.2": {
      "aurelia-loader": "github:aurelia/loader@0.10.0",
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0"
    },
    "github:aurelia/loader@0.10.0": {
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-path": "github:aurelia/path@0.10.0"
    },
    "github:aurelia/logging-console@0.8.0": {
      "aurelia-logging": "github:aurelia/logging@0.8.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0"
    },
    "github:aurelia/metadata@0.9.0": {
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/pal-browser@0.2.0": {
      "aurelia-pal": "github:aurelia/pal@0.2.0"
    },
    "github:aurelia/route-recognizer@0.8.0": {
      "aurelia-path": "github:aurelia/path@0.10.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/router@0.13.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.11.2",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.9.0",
      "aurelia-history": "github:aurelia/history@0.8.0",
      "aurelia-logging": "github:aurelia/logging@0.8.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "aurelia-path": "github:aurelia/path@0.10.0",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.8.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/task-queue@0.8.0": {
      "aurelia-pal": "github:aurelia/pal@0.2.0"
    },
    "github:aurelia/templating-binding@0.16.1": {
      "aurelia-binding": "github:aurelia/binding@0.10.1",
      "aurelia-logging": "github:aurelia/logging@0.8.0",
      "aurelia-templating": "github:aurelia/templating@0.16.0"
    },
    "github:aurelia/templating-resources@0.16.1": {
      "aurelia-binding": "github:aurelia/binding@0.10.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.11.2",
      "aurelia-loader": "github:aurelia/loader@0.10.0",
      "aurelia-logging": "github:aurelia/logging@0.8.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "aurelia-path": "github:aurelia/path@0.10.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.8.0",
      "aurelia-templating": "github:aurelia/templating@0.16.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-router@0.17.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.11.2",
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "aurelia-path": "github:aurelia/path@0.10.0",
      "aurelia-router": "github:aurelia/router@0.13.0",
      "aurelia-templating": "github:aurelia/templating@0.16.0"
    },
    "github:aurelia/templating@0.16.0": {
      "aurelia-binding": "github:aurelia/binding@0.10.1",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.11.2",
      "aurelia-loader": "github:aurelia/loader@0.10.0",
      "aurelia-logging": "github:aurelia/logging@0.8.0",
      "aurelia-metadata": "github:aurelia/metadata@0.9.0",
      "aurelia-pal": "github:aurelia/pal@0.2.0",
      "aurelia-path": "github:aurelia/path@0.10.0",
      "aurelia-task-queue": "github:aurelia/task-queue@0.8.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:brianreavis/selectize.js@0.12.1": {
      "css": "github:systemjs/plugin-css@0.1.18",
      "jquery": "github:components/jquery@2.1.4",
      "microplugin": "npm:microplugin@0.0.3",
      "sifter": "github:brianreavis/sifter.js@0.4.4"
    },
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.5.1"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-os@0.1.0": {
      "os-browserify": "npm:os-browserify@0.1.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:twbs/bootstrap@3.3.5": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "npm:amdefine@1.0.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.25": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:buffer@3.5.1": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:clean-css@3.4.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "commander": "npm:commander@2.8.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "os": "github:jspm/nodelibs-os@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "source-map": "npm:source-map@0.4.4",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:commander@2.8.1": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graceful-readlink": "npm:graceful-readlink@1.0.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.2.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:font-awesome@4.4.0": {
      "css": "github:systemjs/plugin-css@0.1.18"
    },
    "npm:graceful-readlink@1.0.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:os-browserify@0.1.2": {
      "os": "github:jspm/nodelibs-os@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:source-map@0.4.4": {
      "amdefine": "npm:amdefine@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
